@startuml
left to right direction

map FileTracker {
    updated(FileState, File)=>SIGNAL
}

map Console {
    print_file_state(FileState, File)=>SLOT
}

map Logger {
    log_messege(FileState, File)=>SLOT
}

FileTracker::updated ---> Console::print_file_state
FileTracker::updated ---> Logger::log_messege
@enduml
